### ISSUE TITLE
Nice!!!

### ISSUE THREAD

**Issue by ammikeya** [Saber2pr/vsc-ext-todolist#1]
I think it's perfect! I like it,Thank you。Follow and  Star

**Comment by Saber2pr** [comment]
> I think it's perfect! I like it,Thank you。Follow and Star

HaHa, thank you! QVQ, I'm too busy to reply..

I also build a web app for Todo Tree (QVQ): https://fronted-tsx-developer.github.io/demos/todotree/index.html

**Comment by ammikeya** [comment]
Cool!
