### ISSUE TITLE
Add ability to drag/drop between .todo lists

### ISSUE THREAD

**Issue by c835722** [Saber2pr/vsc-ext-todolist#12]
## Feature request

Describe your needs.
I would like to be able to drag an item from one list and place it into another list within an existing sequence.

**Comment by Saber2pr** [comment]
Now dragging items can only be do in one file. If you want move item from the current openning todo to another todo, you can try copy it(ctrl + c),  then open the target todo file and paste it.

**Comment by Saber2pr** [comment]
> ## Feature request
> Describe your needs. I would like to be able to drag an item from one list and place it into another list within an existing sequence.

Now dragging items can only be do in one file. If you want move item from the current openning todo to another todo, you can try copy it(ctrl + c),  then open the target todo file and paste it(ctrl + v).

**Comment by c835722** [comment]
Thank you for the workaround suggestion.
