### ISSUE TITLE
Infinite loading screen - vscode

### ISSUE THREAD

**Issue by rdelian** [Saber2pr/vsc-ext-todolist#14]
## Description
I cannot open any file with the `.todo` file type, the extension is stuck in an infinite loading screen, I even tried with an empty file, same issue

## Platform
Windows

## Version
v0.2.48

## Error Log
From "Runtime Status" in vscode
```
handleMap[service] is not a function
handleMap[service] is not a function
handleMap[service] is not a function
handleMap[service] is not a function
handleMap[service] is not a function
```

![image](https://github.com/Saber2pr/vsc-ext-todolist/assets/25958136/06dc21a8-0b45-4fd2-b4f9-38b7413d04eb)

**Comment by Saber2pr** [comment]
Fixed at v0.2.49. 2023.7.27 11:29AM ~ 

Recently, I have been developing its Electron desktop version and adding a new feature caused this problem. Now it has been fixed. Thank you for the feedback, and I apologize for the inconvenience. Before the next release, I believe I should carefully test its compatibility with VS Code. 😔

**Comment by Saber2pr** [comment]
A new feature at v0.2.49, you can export todo as wiki format ~ like this:

1. Write the todo file:

<img width="554" alt="image" src="https://github.com/Saber2pr/vsc-ext-todolist/assets/40260564/e86154bd-b960-4850-a281-da9899b07f23">

2. Export md from todo, check the "Wiki Format":

<img width="521" alt="image" src="https://github.com/Saber2pr/vsc-ext-todolist/assets/40260564/80916ca0-0b8e-4abf-91ff-e7eafff304bd">

3. The output wiki markdown:

<img width="353" alt="image" src="https://github.com/Saber2pr/vsc-ext-todolist/assets/40260564/4d0cfca9-bf61-4af5-97ca-df2be6669794">

**Comment by rdelian** [comment]
Thanks for the quick reponse and pushed fix, it works like a charm now
