### ISSUE TITLE
does not work anymore

### ISSUE THREAD

**Issue by imperator-maximus** [Saber2pr/vsc-ext-todolist#3]
## Description

Great add-on but it suddenly stopped working. Where can I find the file of my todos now? Thank you

## Platform

Windows. (Remote WSL)

## Version

 v1.0.21.

## Error Log

Srrg+Shift+P and execute "Todo List" there it shows "command 'todolist.main' not found error

I deinstalled and installed again without any sucess.

**Comment by Saber2pr** [comment]
default todo file checkout in path `~/.todolistrc`
```sh
cat  ~/.todolistrc
```

--- 
used in remote ssh/container/wsl

1. ensure enabled in remote environment
<img width="589" alt="截屏2022-02-01 下午2 10 26" src="https://user-images.githubusercontent.com/40260564/151921649-aebc325a-9396-4666-8c56-a9cba365c713.png">


2. then execute "Todo List" 
<img width="838" alt="截屏2022-02-01 下午2 08 34" src="https://user-images.githubusercontent.com/40260564/151921117-d6d0a265-245b-48d5-913d-709c191f1edf.png">

or click the status bar:
<img width="247" alt="截屏2022-02-01 下午2 17 11" src="https://user-images.githubusercontent.com/40260564/151921518-9fd04128-53e5-4539-8cf9-29966c7b0447.png">
