### ISSUE TITLE
Poor Performance

### ISSUE THREAD

**Issue by rdelian** [Saber2pr/vsc-ext-todolist#5]
## Description

Performance is very bad when trying to arrange/move tasks, I have 84 todo entries

I have noticed that if I fold all my main todo categories performance is fine, but as soon as the extension has to draw more todo entries performance degrades to almost unusable

Let me know if I should provide any logs/tests info

## Platform

Windows

## Version

v0.1.20

## Error Log

\-

**Comment by Saber2pr** [comment]
For the long todolist, you can try to `Enable virtual scrolling`,"settings -> Enable virtual scrolling"
> Improved response speed, but reduced scrolling performance. (recommended for a long list)
![image](https://user-images.githubusercontent.com/40260564/160229666-139ddad5-772e-4a3d-99e7-e495a374fe00.png)

**Comment by rdelian** [comment]
That improved the performance, thank you 👍🏼
