### ISSUE TITLE
Add the ability to select a file, whose progress will be displayed in a status bar

### ISSUE THREAD

**Issue by tembun** [Saber2pr/vsc-ext-todolist#6]
## Feature request
I have 2 .todo files in my workspace and I want to select a file whose progress I want to see in the status bar and change it to another one when it necessary.

What do you think about this idea?

**Comment by Saber2pr** [comment]
Good idea! I've thought about that too. wait a week or soon ~

**Comment by Saber2pr** [comment]
> Good idea! I've thought about that too. wait a week or soon ~

published v0.1.22
> Settings -> StatusBar -> Set

**Comment by tembun** [comment]
It works! Thank You!
