### ISSUE TITLE
Keybinds

### ISSUE THREAD

**Issue by MrMoine** [Saber2pr/vsc-ext-todolist#7]
The extension is great I really like it but I wondered if it'd be possible to add some simple keybind integration (as simple as "enter" to create a new task or the arrows to select one, "delete" to delete it etc).

**Comment by Saber2pr** [comment]
Thanks for suggestion. Keybinding is a good idea👍, maybe supported within a week!

**Comment by Saber2pr** [comment]
> The extension is great I really like it but I wondered if it'd be possible to add some simple keybind integration (as simple as "enter" to create a new task or the arrows to select one, "delete" to delete it etc).

published v0.1.26. see Settings > Shotcuts
